import Image from 'next/image';

import Curve from '@/components/Curve';
import Head from 'next/head';
import PresentHero from '@/components/Front-page/present-hero';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Curve backgroundColor={'#154c79'}>
				<div className="top">
					<div className="text-white text-center text-3xl font-bold">
						<div className="top-5 text-center mt-5"></div>

						<div className="bg-blue-700">ALL EXPLORE - BANSKO</div>

						<Image src="/poster1.jpg" width={1000} height={500} alt="top" />
						<div className="bg-blue-700">AI PLANER</div>
						<button className="mt-2 ml-48"></button>

						<PresentHero />
					</div>
				</div>
			</Curve>
		</>
	);
}
