import Image from 'next/image';
import { Inter } from 'next/font/google';
import Curve from '@/components/Curve';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Curve backgroundColor={'#B0AD98'}>
				<div className="top">
					<div className="text-white text-center text-3xl font-bold">
						<div className="top-5 text-center mt-5">ALL EXPLORE - BANSKO</div>
						<Image src="/poster1.jpg" width={1000} height={500} alt="top" />
					</div>
				</div>
			</Curve>
		</>
	);
}
